version: '2'

services:
  database:
    image: mariadb:10.6
    container_name: rivers-db
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      MARIADB_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
  ingest:
    build: ./Ingest/
    depends_on:
      - "database"
    container_name: rivers-in
    command: python getData.py
    environment:
      CLEAR_DATABASE_FIRST: "y"
      CREATE_TABLES: "ANY_VALUE_HERE_IS_TRUE"
      CREATE_DATABASE: "y"
      INSERT_SITES: "y"
      INSERT_OBSERVATIONS: "y"
      PRINT_DATA: "y"
      DO_PREDICT: "y"
  web:
    build:
      context: ./Web/
      args:
        JAR_FILE: ./target/rivers-0.0.1-SNAPSHOT.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://rivers-db:3306/rivers?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=toor
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    container_name: rivers-web
  front:
    build: ./Frontend/
    ports:
      - "8081:80"
    depends_on:
      - "web"
    container_name: rivers-front
