version: '2'

services:
  database:
    image: mariadb:10.6
    container_name: rivers-db
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      MARIADB_ROOT_PASSWORD: toor
  ingest:
    build: ./RiversFetch/
    depends_on:
      - "database"
    container_name: rivers-in
    command: python getData.py
    environment:
      #CREATE_TABLES: "ANY_VALUE_HERE_IS_TRUE"
      #CREATE_DATABASE: "y"
      #INSERT_SITES: "y"
      #INSERT_OBSERVATIONS: "y"
      PRINT_DATA: "y"
